In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load Data
(Raw from competition)

In [ ]:
# load train & test sets (raw)
train = pd.read_csv('/content/drive/MyDrive/BDML-2024/P-Set2/data/train_hogares.csv')
test = pd.read_csv('/content/drive/MyDrive/BDML-2024/P-Set2/data/test_hogares.csv')

# person-level datasets
train_person = pd.read_csv('/content/drive/MyDrive/BDML-2024/P-Set2/data/train_personas.csv')
test_person = pd.read_csv('/content/drive/MyDrive/BDML-2024/P-Set2/data/test_personas.csv')

train.columns, test.columns, train_person.columns, test_person.columns

(Index(['id', 'Clase', 'Dominio', 'P5000', 'P5010', 'P5090', 'P5100', 'P5130',
        'P5140', 'Nper', 'Npersug', 'Ingtotug', 'Ingtotugarr', 'Ingpcug', 'Li',
        'Lp', 'Pobre', 'Indigente', 'Npobres', 'Nindigentes', 'Fex_c', 'Depto',
        'Fex_dpto'],
       dtype='object'),
 Index(['id', 'Clase', 'Dominio', 'P5000', 'P5010', 'P5090', 'P5100', 'P5130',
        'P5140', 'Nper', 'Npersug', 'Li', 'Lp', 'Fex_c', 'Depto', 'Fex_dpto'],
       dtype='object'),
 Index(['id', 'Orden', 'Clase', 'Dominio', 'Estrato1', 'P6020', 'P6040',
        'P6050', 'P6090', 'P6100',
        ...
        'Iof2es', 'Iof3hes', 'Iof3ies', 'Iof6es', 'Ingtotob', 'Ingtotes',
        'Ingtot', 'Fex_c', 'Depto', 'Fex_dpto'],
       dtype='object', length=135),
 Index(['id', 'Orden', 'Clase', 'Dominio', 'P6020', 'P6040', 'P6050', 'P6090',
        'P6100', 'P6210', 'P6210s1', 'P6240', 'Oficio', 'P6426', 'P6430',
        'P6510', 'P6545', 'P6580', 'P6585s1', 'P6585s2', 'P6585s3', 'P6585s4',
        'P6590', 'P6600', 'P6610', 'P6620', 'P6630s1', 'P6630s2', 'P6630s3',
        'P6630s4', 'P6630s6', 'P6800', 'P6870', 'P6920', 'P7040', 'P7045',
        'P7050', 'P7090', 'P7110', 'P7120', 'P7150', 'P7160', 'P7310', 'P7350',
        'P7422', 'P7472', 'P7495', 'P7500s2', 'P7500s3', 'P7505', 'P7510s1',
        'P7510s2', 'P7510s3', 'P7510s5', 'P7510s6', 'P7510s7', 'Pet', 'Oc',
        'Des', 'Ina', 'Fex_c', 'Depto', 'Fex_dpto'],
       dtype='object'))

# 2. Variable Creations

## 2.1. Mean Age of Household

In [ ]:
# Aggregate age for train set
train_age_agg = train_person.groupby('id')['P6040'].mean().reset_index()
train_age_agg = train_age_agg.rename(columns={'P6040': 'mean_age_household'})

# Merge aggregated age with train set
train = train.merge(train_age_agg, on='id', how='left')

# Aggregate age for test set
test_age_agg = test_person.groupby('id')['P6040'].mean().reset_index()
test_age_agg = test_age_agg.rename(columns={'P6040': 'mean_age_household'})

# Merge aggregated age with test set
test = test.merge(test_age_agg, on='id', how='left')

train.head(10)

,id,Clase,Dominio,P5000,P5010,P5090,P5100,P5130,P5140,Nper,...,Li,Lp,Pobre,Indigente,Npobres,Nindigentes,Fex_c,Depto,Fex_dpto,mean_age_household
0,8d0193e328305a042001a35f,1,MEDELLIN,4,2,1,NaN,400000.0,NaN,5,...,122809.534158,289878.24715,0,0,0,0,127.222038,5,146.251790,19.200000
1,cf7491d7f2cc9c216bd009e7,1,MEDELLIN,5,4,3,NaN,NaN,250000.0,4,...,122809.534158,289878.24715,1,0,4,0,115.866093,5,93.080952,52.750000
2,d90a57f64d2a84dbacbed2a5,1,MEDELLIN,4,2,1,NaN,700000.0,NaN,3,...,122809.534158,289878.24715,0,0,0,0,100.123276,5,89.637086,53.000000
3,db34e387a94a783188ab3a33,1,MEDELLIN,3,1,1,NaN,450000.0,NaN,1,...,122809.534158,289878.24715,0,0,0,0,108.829812,5,95.584376,43.000000
4,97bbef785824746ecab09c6f,1,MEDELLIN,4,3,3,NaN,NaN,500000.0,5,...,122809.534158,289878.24715,1,0,5,0,110.412859,5,124.560515,34.200000
5,39f55224baf37c9359bbba8f,1,MEDELLIN,3,2,1,NaN,400000.0,NaN,3,...,122809.534158,289878.24715,0,0,0,0,91.694911,5,81.112706,39.333333
6,5c89726bd105e851ae35a477,1,MEDELLIN,4,1,1,NaN,700000.0,NaN,1,...,122809.534158,289878.24715,0,0,0,0,98.474144,5,94.045486,48.000000
7,4a361658f7697f81f52b5e2c,1,MEDELLIN,4,3,1,NaN,750000.0,NaN,4,...,122809.534158,289878.24715,0,0,0,0,110.792831,5,92.756218,36.000000
8,5f31532ad803e6b0ad2b98f8,1,MEDELLIN,4,3,1,NaN,600000.0,NaN,4,...,122809.534158,289878.24715,0,0,0,0,86.898204,5,77.680538,31.000000
9,d7e0fe34bb5ed1d675fa4bdd,1,MEDELLIN,4,1,3,NaN,NaN,270000.0,2,...,122809.534158,289878.24715,0,0,0,0,93.492882,5,81.580146,23.500000

## 2.2. Social Safety Net Dummy

In [ ]:
# Function to check if any value is 1 (has social program)
def any_has_program(x):
    return (x == 1).any()

# Aggregate social program affiliation for train set
train_social_agg = train_person.groupby('id')['P6090'].agg(any_has_program).reset_index()
train_social_agg = train_social_agg.rename(columns={'P6090': 'has_social_program'})

# Merge aggregated data with train set
train = train.merge(train_social_agg, on='id', how='left')

# Aggregate social program affiliation for test set
test_social_agg = test_person.groupby('id')['P6090'].agg(any_has_program).reset_index()
test_social_agg = test_social_agg.rename(columns={'P6090': 'has_social_program'})

# Merge aggregated data with test set
test = test.merge(test_social_agg, on='id', how='left')

# Ensure 'has_social_program' is binary (0 or 1)
train['has_social_program'] = train['has_social_program'].fillna(False).astype(int)
test['has_social_program'] = test['has_social_program'].fillna(False).astype(int)

## 2.3. Household Education Level

In [ ]:
# Function to map education levels to numeric values
def map_education_level(x):
    if pd.isna(x):
        return 0
    # P6210 is already numeric, but we'll subtract 1 to make it 0-indexed
    # This way, the lowest education level (2) becomes 1, and the highest (9) becomes 8
    return max(0, int(x) - 1)

# Apply mapping and sum education levels for train set
train_person['educ_value'] = train_person['P6210'].apply(map_education_level)
train_educ_agg = train_person.groupby('id')['educ_value'].sum().reset_index()
train_educ_agg = train_educ_agg.rename(columns={'educ_value': 'educ_attainment'})

# Merge aggregated data with train set
train = train.merge(train_educ_agg, on='id', how='left')

# Apply mapping and sum education levels for test set
test_person['educ_value'] = test_person['P6210'].apply(map_education_level)
test_educ_agg = test_person.groupby('id')['educ_value'].sum().reset_index()
test_educ_agg = test_educ_agg.rename(columns={'educ_value': 'educ_attainment'})

# Merge aggregated data with test set
test = test.merge(test_educ_agg, on='id', how='left')

# Fill NaN values with 0 (for households with no education data)
train['educ_attainment'] = train['educ_attainment'].fillna(0)
test['educ_attainment'] = test['educ_attainment'].fillna(0)

## 2.4. Work-Based Features

In [ ]:
# Define functions for each aggregation
def someone_works(x):
    return (x == 1).any()

def unemployment_rate(x):
    total = len(x)
    working = (x == 1).sum()
    seeking = (x == 2).sum()
    return seeking / (working + seeking) if (working + seeking) > 0 else 0

def main_activity(x):
    x = x.dropna()
    if x.empty:
        return 0
    mode_result = x.mode()
    return mode_result.iloc[0] if not mode_result.empty else 0

def diversity_index(x):
    x = x.dropna()
    if x.empty:
        return 0
    _, counts = np.unique(x, return_counts=True)
    return 1 - np.sum((counts / len(x)) ** 2)

# Aggregate data for train set
train_activity_agg = train_person.groupby('id').agg({
    'P6240': [
        ('someone_works', someone_works),
        ('unemployment_rate', unemployment_rate),
        ('main_household_activity', main_activity),
        ('activity_diversity', diversity_index)
    ]
}).reset_index()

# Flatten column names
train_activity_agg.columns = ['_'.join(col).strip() for col in train_activity_agg.columns.values]
train_activity_agg = train_activity_agg.rename(columns={'id_': 'id'})

# Merge aggregated data with train set
train = train.merge(train_activity_agg, on='id', how='left')

# Repeat the process for test set
test_activity_agg = test_person.groupby('id').agg({
    'P6240': [
        ('someone_works', someone_works),
        ('unemployment_rate', unemployment_rate),
        ('main_household_activity', main_activity),
        ('activity_diversity', diversity_index)
    ]
}).reset_index()

test_activity_agg.columns = ['_'.join(col).strip() for col in test_activity_agg.columns.values]
test_activity_agg = test_activity_agg.rename(columns={'id_': 'id'})

test = test.merge(test_activity_agg, on='id', how='left')

# Fill NaN values
for col in ['P6240_someone_works', 'P6240_unemployment_rate', 'P6240_main_household_activity', 'P6240_activity_diversity']:
    train[col] = train[col].fillna(0)
    test[col] = test[col].fillna(0)

In [ ]:
train.head(15)

,id,Clase,Dominio,P5000,P5010,P5090,P5100,P5130,P5140,Nper,...,Fex_c,Depto,Fex_dpto,mean_age_household,has_social_program,educ_attainment,P6240_someone_works,P6240_unemployment_rate,P6240_main_household_activity,P6240_activity_diversity
0,8d0193e328305a042001a35f,1,MEDELLIN,4,2,1,NaN,400000.0,NaN,5,...,127.222038,5,146.251790,19.200000,1,11,True,0.000000,1.0,0.500000
1,cf7491d7f2cc9c216bd009e7,1,MEDELLIN,5,4,3,NaN,NaN,250000.0,4,...,115.866093,5,93.080952,52.750000,1,5,False,0.000000,6.0,0.375000
2,d90a57f64d2a84dbacbed2a5,1,MEDELLIN,4,2,1,NaN,700000.0,NaN,3,...,100.123276,5,89.637086,53.000000,1,10,True,0.000000,6.0,0.444444
3,db34e387a94a783188ab3a33,1,MEDELLIN,3,1,1,NaN,450000.0,NaN,1,...,108.829812,5,95.584376,43.000000,1,2,False,0.000000,6.0,0.000000
4,97bbef785824746ecab09c6f,1,MEDELLIN,4,3,3,NaN,NaN,500000.0,5,...,110.412859,5,124.560515,34.200000,1,10,True,0.000000,1.0,0.444444
5,39f55224baf37c9359bbba8f,1,MEDELLIN,3,2,1,NaN,400000.0,NaN,3,...,91.694911,5,81.112706,39.333333,1,12,True,0.333333,1.0,0.444444
6,5c89726bd105e851ae35a477,1,MEDELLIN,4,1,1,NaN,700000.0,NaN,1,...,98.474144,5,94.045486,48.000000,1,5,True,0.000000,1.0,0.000000
7,4a361658f7697f81f52b5e2c,1,MEDELLIN,4,3,1,NaN,750000.0,NaN,4,...,110.792831,5,92.756218,36.000000,1,20,True,0.000000,1.0,0.750000
8,5f31532ad803e6b0ad2b98f8,1,MEDELLIN,4,3,1,NaN,600000.0,NaN,4,...,86.898204,5,77.680538,31.000000,1,17,True,0.000000,3.0,0.625000
9,d7e0fe34bb5ed1d675fa4bdd,1,MEDELLIN,4,1,3,NaN,NaN,270000.0,2,...,93.492882,5,81.580146,23.500000,1,10,True,0.000000,1.0,0.500000
10,55b38e205b95ed0c21b5e81f,1,MEDELLIN,1,1,3,NaN,NaN,350000.0,1,...,73.359246,5,64.143748,21.000000,1,5,True,0.000000,1.0,0.000000
11,4a6aa0ad9d70c696e0e85892,1,MEDELLIN,1,1,3,NaN,NaN,280000.0,1,...,73.359246,5,64.143748,22.000000,1,5,True,0.000000,1.0,0.000000
12,6618680f614d39c58c1ffaeb,1,MEDELLIN,4,3,1,NaN,350000.0,NaN,3,...,83.413769,5,76.933822,48.333333,1,12,True,0.000000,1.0,0.666667
13,09542460ec63684b0b29f64e,1,MEDELLIN,3,1,1,NaN,550000.0,NaN,2,...,98.750699,5,90.938052,58.000000,1,8,True,0.000000,1.0,0.500000
14,d0cc1518e31fbf52393cb60b,1,MEDELLIN,3,2,3,NaN,NaN,700000.0,3,...,115.589538,5,96.188386,44.666667,1,12,True,0.000000,1.0,0.666667

## 2.5. Subsidies

In [ ]:
def aggregate_subsidies(group):
    subsidy_columns = ['P6585s1', 'P6585s2', 'P6585s3', 'P6585s4']
    return pd.Series({
        'has_food_subsidy': (group['P6585s1'] == 1).any(),
        'has_transport_subsidy': (group['P6585s2'] == 1).any(),
        'has_family_subsidy': (group['P6585s3'] == 1).any(),
        'has_school_subsidy': (group['P6585s4'] == 1).any(),
        'total_subsidies': sum((group[col] == 1).any() for col in subsidy_columns)
    })

# Aggregate subsidies for train set
train_subsidies_agg = train_person.groupby('id').apply(aggregate_subsidies).reset_index()

# Merge aggregated data with train set
train = train.merge(train_subsidies_agg, on='id', how='left')

# Aggregate subsidies for test set
test_subsidies_agg = test_person.groupby('id').apply(aggregate_subsidies).reset_index()

# Merge aggregated data with test set
test = test.merge(test_subsidies_agg, on='id', how='left')

# Convert boolean columns to int (0 or 1)
boolean_columns = ['has_food_subsidy', 'has_transport_subsidy', 'has_family_subsidy', 'has_school_subsidy']
for col in boolean_columns:
    train[col] = train[col].astype(int)
    test[col] = test[col].astype(int)

<ipython-input-55-babaa17f6cd3>:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_subsidies_agg = train_person.groupby('id').apply(aggregate_subsidies).reset_index()
<ipython-input-55-babaa17f6cd3>:18: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_subsidies_agg = test_person.groupby('id').apply(aggregate_subsidies).reset_index()

## 2.6. Pension Contribution

In [ ]:
def aggregate_pension_status(group):
    p6920 = group['P6920']

    # Check if all values are missing
    if p6920.isnull().all():
        return pd.Series({
            'has_pension_contributor': np.nan,
            'has_pensioner': np.nan,
            'prop_pension_contributors': np.nan,
            'prop_pensioners': np.nan,
            'pension_status': np.nan
        })

    # If at least one value is not missing, treat missing as 2 (not contributing)
    p6920_filled = p6920.fillna(2)

    total_members = len(p6920_filled)
    contributors = (p6920_filled == 1).sum()
    non_contributors = (p6920_filled == 2).sum()
    pensioners = (p6920_filled == 3).sum()

    return pd.Series({
        'has_pension_contributor': contributors > 0,
        'has_pensioner': pensioners > 0,
        'prop_pension_contributors': contributors / total_members,
        'prop_pensioners': pensioners / total_members,
        'pension_status': 'mixed' if (contributors > 0 and (non_contributors > 0 or pensioners > 0)) else
                          'all_contributing' if contributors == total_members else
                          'all_pensioners' if pensioners == total_members else
                          'none' if non_contributors == total_members else 'other'
    })

# Aggregate pension status for train set
train_pension_agg = train_person.groupby('id').apply(aggregate_pension_status).reset_index()

# Merge aggregated data with train set
train = train.merge(train_pension_agg, on='id', how='left')

# Aggregate pension status for test set
test_pension_agg = test_person.groupby('id').apply(aggregate_pension_status).reset_index()

# Merge aggregated data with test set
test = test.merge(test_pension_agg, on='id', how='left')

# Convert boolean columns to int (0 or 1), keeping NaN as is
boolean_columns = ['has_pension_contributor', 'has_pensioner']
for col in boolean_columns:
    train[col] = train[col].astype('Int64')  # This allows for NaN values
    test[col] = test[col].astype('Int64')

<ipython-input-56-4a2e96bff8fb>:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_pension_agg = train_person.groupby('id').apply(aggregate_pension_status).reset_index()
<ipython-input-56-4a2e96bff8fb>:40: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_pension_agg = test_person.groupby('id').apply(aggregate_pension_status).reset_index()

## 2.7. Household Size

In [ ]:
# Calculate household size for train set
train_size = train_person.groupby('id').size().reset_index(name='household_size')
train = train.merge(train_size, on='id', how='left')

# Calculate household size for test set
test_size = test_person.groupby('id').size().reset_index(name='household_size')
test = test.merge(test_size, on='id', how='left')

## 2.8. Dependency Ratio

In [ ]:
def calculate_dependency_ratio(group):
    working_age = ((group['P6040'] >= 15) & (group['P6040'] <= 64)).sum()
    dependents = (group['P6040'] < 15).sum() + (group['P6040'] > 64).sum()
    return dependents / working_age if working_age > 0 else np.inf

# Calculate dependency ratio for train set
train_dependency = train_person.groupby('id').apply(calculate_dependency_ratio).reset_index(name='dependency_ratio')
train = train.merge(train_dependency, on='id', how='left')

# Calculate dependency ratio for test set
test_dependency = test_person.groupby('id').apply(calculate_dependency_ratio).reset_index(name='dependency_ratio')
test = test.merge(test_dependency, on='id', how='left')

<ipython-input-58-9930f95a40a8>:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_dependency = train_person.groupby('id').apply(calculate_dependency_ratio).reset_index(name='dependency_ratio')
<ipython-input-58-9930f95a40a8>:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_dependency = test_person.groupby('id').apply(calculate_dependency_ratio).reset_index(name='dependency_ratio')

## 2.9. Female Head of Household

In [ ]:
def is_female_headed(group):
    head = group[group['P6050'] == 1]
    return (head['P6020'] == 2).any() if not head.empty else False

# Calculate female-headed household for train set
train_female_headed = train_person.groupby('id').apply(is_female_headed).reset_index(name='is_female_headed')
train = train.merge(train_female_headed, on='id', how='left')

# Calculate female-headed household for test set
test_female_headed = test_person.groupby('id').apply(is_female_headed).reset_index(name='is_female_headed')
test = test.merge(test_female_headed, on='id', how='left')

<ipython-input-59-67be1e27fd9c>:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_female_headed = train_person.groupby('id').apply(is_female_headed).reset_index(name='is_female_headed')
<ipython-input-59-67be1e27fd9c>:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_female_headed = test_person.groupby('id').apply(is_female_headed).reset_index(name='is_female_headed')

## 2.10. Health Insurance Coverage

In [ ]:
def aggregate_health_insurance(group):
    has_insurance = (group['P6090'] == 1).any()
    insurance_types = group[group['P6090'] == 1]['P6100'].value_counts()
    main_type = insurance_types.index[0] if not insurance_types.empty else 0
    return pd.Series({
        'has_health_insurance': has_insurance,
        'main_insurance_type': main_type,
        'insurance_coverage_rate': (group['P6090'] == 1).mean()
    })

# Calculate health insurance features for train set
train_health_insurance = train_person.groupby('id').apply(aggregate_health_insurance).reset_index()
train = train.merge(train_health_insurance, on='id', how='left')

# Calculate health insurance features for test set
test_health_insurance = test_person.groupby('id').apply(aggregate_health_insurance).reset_index()
test = test.merge(test_health_insurance, on='id', how='left')

<ipython-input-60-6afb798e98c2>:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_health_insurance = train_person.groupby('id').apply(aggregate_health_insurance).reset_index()
<ipython-input-60-6afb798e98c2>:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_health_insurance = test_person.groupby('id').apply(aggregate_health_insurance).reset_index()

In [ ]:
train.head(10)

,id,Clase,Dominio,P5000,P5010,P5090,P5100,P5130,P5140,Nper,...,has_pensioner,prop_pension_contributors,prop_pensioners,pension_status,household_size,dependency_ratio,is_female_headed,has_health_insurance,main_insurance_type,insurance_coverage_rate
0,8d0193e328305a042001a35f,1,MEDELLIN,4,2,1,NaN,400000.0,NaN,5,...,0,0.400000,0.0,mixed,5,1.5,False,True,1.0,0.400000
1,cf7491d7f2cc9c216bd009e7,1,MEDELLIN,5,4,3,NaN,NaN,250000.0,4,...,<NA>,NaN,NaN,NaN,4,0.0,False,True,3.0,1.000000
2,d90a57f64d2a84dbacbed2a5,1,MEDELLIN,4,2,1,NaN,700000.0,NaN,3,...,0,0.000000,0.0,none,3,0.5,True,True,1.0,0.666667
3,db34e387a94a783188ab3a33,1,MEDELLIN,3,1,1,NaN,450000.0,NaN,1,...,0,0.000000,0.0,none,1,0.0,False,True,3.0,1.000000
4,97bbef785824746ecab09c6f,1,MEDELLIN,4,3,3,NaN,NaN,500000.0,5,...,0,0.000000,0.0,none,5,4.0,False,True,1.0,0.600000
5,39f55224baf37c9359bbba8f,1,MEDELLIN,3,2,1,NaN,400000.0,NaN,3,...,0,0.666667,0.0,mixed,3,0.0,False,True,1.0,1.000000
6,5c89726bd105e851ae35a477,1,MEDELLIN,4,1,1,NaN,700000.0,NaN,1,...,0,1.000000,0.0,all_contributing,1,0.0,True,True,2.0,1.000000
7,4a361658f7697f81f52b5e2c,1,MEDELLIN,4,3,1,NaN,750000.0,NaN,4,...,0,0.500000,0.0,mixed,4,0.0,False,True,1.0,1.000000
8,5f31532ad803e6b0ad2b98f8,1,MEDELLIN,4,3,1,NaN,600000.0,NaN,4,...,0,0.250000,0.0,mixed,4,0.0,False,True,1.0,1.000000
9,d7e0fe34bb5ed1d675fa4bdd,1,MEDELLIN,4,1,3,NaN,NaN,270000.0,2,...,0,0.500000,0.0,mixed,2,0.0,False,True,1.0,0.500000

## 2.11. More Age-related Features

In [ ]:
def calculate_age_features(group):
    return pd.Series({
        'num_individuals': len(group),
        'num_under_18': (group['P6040'] < 18).sum(),
        'num_over_65': (group['P6040'] > 65).sum(),
        'has_over_65': (group['P6040'] > 65).any(),
    })

# Calculate age-related features for train set
train_age_features = train_person.groupby('id').apply(calculate_age_features).reset_index()
train = train.merge(train_age_features, on='id', how='left')

# Calculate age-related features for test set
test_age_features = test_person.groupby('id').apply(calculate_age_features).reset_index()
test = test.merge(test_age_features, on='id', how='left')

# Convert boolean to integer
train['has_over_65'] = train['has_over_65'].astype(int)
test['has_over_65'] = test['has_over_65'].astype(int)

<ipython-input-62-cf6e4773ea88>:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_age_features = train_person.groupby('id').apply(calculate_age_features).reset_index()
<ipython-input-62-cf6e4773ea88>:14: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_age_features = test_person.groupby('id').apply(calculate_age_features).reset_index()

## 2.12. More Education-related Features

In [ ]:
def has_higher_education(group):
    return (group['P6210'] == 6).any()

# Calculate higher education feature for train set
train_education = train_person.groupby('id').apply(has_higher_education).reset_index(name='has_university_education')
train = train.merge(train_education, on='id', how='left')

# Calculate higher education feature for test set
test_education = test_person.groupby('id').apply(has_higher_education).reset_index(name='has_university_education')
test = test.merge(test_education, on='id', how='left')

# Convert boolean to integer
train['has_university_education'] = train['has_university_education'].astype(int)
test['has_university_education'] = test['has_university_education'].astype(int)

<ipython-input-63-e1e87c5237bf>:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_education = train_person.groupby('id').apply(has_higher_education).reset_index(name='has_university_education')
<ipython-input-63-e1e87c5237bf>:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_education = test_person.groupby('id').apply(has_higher_education).reset_index(name='has_university_education')

## 2.14. Food Payment

In [ ]:
def receives_food_payment(group):
    return (group['P6590'] == 1).any()

# Calculate food payment feature for train set
train_food = train_person.groupby('id').apply(receives_food_payment).reset_index(name='receives_food_payment')
train = train.merge(train_food, on='id', how='left')

# Calculate food payment feature for test set
test_food = test_person.groupby('id').apply(receives_food_payment).reset_index(name='receives_food_payment')
test = test.merge(test_food, on='id', how='left')

# Convert boolean to integer and fill NaN with 0
train['receives_food_payment'] = train['receives_food_payment'].astype(int).fillna(0)
test['receives_food_payment'] = test['receives_food_payment'].astype(int).fillna(0)

<ipython-input-64-60a942c39634>:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_food = train_person.groupby('id').apply(receives_food_payment).reset_index(name='receives_food_payment')
<ipython-input-64-60a942c39634>:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_food = test_person.groupby('id').apply(receives_food_payment).reset_index(name='receives_food_payment')

In [ ]:
train.head(15)

,id,Clase,Dominio,P5000,P5010,P5090,P5100,P5130,P5140,Nper,...,is_female_headed,has_health_insurance,main_insurance_type,insurance_coverage_rate,num_individuals,num_under_18,num_over_65,has_over_65,has_university_education,receives_food_payment
0,8d0193e328305a042001a35f,1,MEDELLIN,4,2,1,NaN,400000.0,NaN,5,...,False,True,1.0,0.400000,5,3,0,0,0,1
1,cf7491d7f2cc9c216bd009e7,1,MEDELLIN,5,4,3,NaN,NaN,250000.0,4,...,False,True,3.0,1.000000,4,0,0,0,0,0
2,d90a57f64d2a84dbacbed2a5,1,MEDELLIN,4,2,1,NaN,700000.0,NaN,3,...,True,True,1.0,0.666667,3,0,1,1,1,0
3,db34e387a94a783188ab3a33,1,MEDELLIN,3,1,1,NaN,450000.0,NaN,1,...,False,True,3.0,1.000000,1,0,0,0,0,0
4,97bbef785824746ecab09c6f,1,MEDELLIN,4,3,3,NaN,NaN,500000.0,5,...,False,True,1.0,0.600000,5,2,1,1,1,0
5,39f55224baf37c9359bbba8f,1,MEDELLIN,3,2,1,NaN,400000.0,NaN,3,...,False,True,1.0,1.000000,3,0,0,0,0,1
6,5c89726bd105e851ae35a477,1,MEDELLIN,4,1,1,NaN,700000.0,NaN,1,...,True,True,2.0,1.000000,1,0,0,0,1,0
7,4a361658f7697f81f52b5e2c,1,MEDELLIN,4,3,1,NaN,750000.0,NaN,4,...,False,True,1.0,1.000000,4,0,0,0,1,0
8,5f31532ad803e6b0ad2b98f8,1,MEDELLIN,4,3,1,NaN,600000.0,NaN,4,...,False,True,1.0,1.000000,4,1,0,0,1,0
9,d7e0fe34bb5ed1d675fa4bdd,1,MEDELLIN,4,1,3,NaN,NaN,270000.0,2,...,False,True,1.0,0.500000,2,0,0,0,1,0
10,55b38e205b95ed0c21b5e81f,1,MEDELLIN,1,1,3,NaN,NaN,350000.0,1,...,False,True,1.0,1.000000,1,0,0,0,1,0
11,4a6aa0ad9d70c696e0e85892,1,MEDELLIN,1,1,3,NaN,NaN,280000.0,1,...,True,True,1.0,1.000000,1,0,0,0,1,0
12,6618680f614d39c58c1ffaeb,1,MEDELLIN,4,3,1,NaN,350000.0,NaN,3,...,False,True,1.0,1.000000,3,0,0,0,1,0
13,09542460ec63684b0b29f64e,1,MEDELLIN,3,1,1,NaN,550000.0,NaN,2,...,False,True,1.0,1.000000,2,0,0,0,1,0
14,d0cc1518e31fbf52393cb60b,1,MEDELLIN,3,2,3,NaN,NaN,700000.0,3,...,False,True,1.0,1.000000,3,0,0,0,1,0

In [ ]:
# store as csv
train.to_csv('/content/drive/MyDrive/BDML-2024/P-Set2/data/train_enhanced.csv', index=False)
test.to_csv('/content/drive/MyDrive/BDML-2024/P-Set2/data/test_enhanced.csv', index=False)

# 3. Data Imputation

In [13]:
# load enhanced datasets
train = pd.read_csv('/content/drive/MyDrive/BDML-2024/P-Set2/data/enhanced/train_enhanced.csv')
test = pd.read_csv('/content/drive/MyDrive/BDML-2024/P-Set2/data/enhanced/test_enhanced.csv')

In [ ]:
# Store the original number of columns in train
original_train_columns = train.columns.tolist()

# Select columns from train that are in test, plus 'Pobre'
train = train[test.columns.tolist() + ['Pobre']]

In [ ]:
train.shape, test.shape

((164960, 46), (66168, 45))

In [14]:
# drop variables P5100, P5130 and P5140 -- many missing
train = train.drop(['P5100', 'P5130', 'P5140'], axis=1)
test = test.drop(['P5100', 'P5130', 'P5140'], axis=1)

In [17]:
# impute missings with 0
train = train.fillna(0)
test = test.fillna(0)

train.shape, test.shape

((164960, 49), (66168, 42))

In [18]:
# drop rows where there is a missing
train = train.dropna()
test = test.dropna()
train.shape, test.shape

((164960, 49), (66168, 42))

In [19]:
# are there missing values?
train.isna().sum().sum(), test.isna().sum().sum()

(0, 0)

In [20]:
# count how many infinites
train.isin([np.inf, -np.inf]).sum().sum(), test.isin([np.inf, -np.inf]).sum().sum()

(0, 0)

# 4. Store Datasets

In [21]:
train.to_csv('/content/drive/MyDrive/BDML-2024/P-Set2/data/imputed_no_missings/train_ready.csv', index=False)
test.to_csv('/content/drive/MyDrive/BDML-2024/P-Set2/data/imputed_no_missings/test_ready.csv', index=False)

In [ ]:
### finis